feat: Rework details page and make it suitable for mobile devices
alphahorizonio/consumat.io-frontend pull request #29
Opened 2021-05-10 02:23 UTC by lucas-goldner

Closes https://github.com/alphahorizonio/consumat.io/issues/60

2021-05-12 21:06 UTC, helmrich requested changes
We already talked about the changes we should make before merging in the meeting. So if you remove the `defaultLayout` prop from the `Layout` component and make minor changes like the addition of a loading spinner to the movie details view we could merge and then continue tweaking/rewriting the detail view and make additions like the watch status, rating functionality, etc. :smile:

2021-05-12 21:10 UTC, helmrich requested changes

2021-05-12 21:10 UTC, helmrich commented on components/Layout.tsx
> +const Layout = ({ children, defaultLayout }: LayoutProps) => {
We should maybe remove this for now as it's not worth having a property that just affects one page in a wrapper component that's related to all pages in my opinion.

2021-05-13 14:01 UTC, lucas-goldner commented
Hey I made the requested changes:
- Added the spinner to the movie details 
- Removed the defaultLayout and changed the styles so it fits better with the new maxWidth now

2021-05-13 14:53 UTC, helmrich approved these changes
LGTM

2021-05-13 14:53 UTC, merged